import 'NewsDetails.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';
import 'dart:convert';

class GlobalNews extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Global(),
    );
  }
}

class Global extends StatefulWidget {
  @override
  _GlobalState createState() => _GlobalState();
}

class _GlobalState extends State<Global> {
  String apiKey = 'e452f52f81984a5f82e6645572903d4d';
  // Autogenerated a;
  var response;
  NewsDetails nsd;
  List<NewsDetails> news = [];

  @override
  void initState() {
    super.initState();
    fetchNews();
  }

  Future<void> fetchNews() async {
    response = await http.get(Uri.parse(
        ("https://newsapi.org/v2/everything?q=global&language=en&apiKey=" +
            apiKey)));
    var data = jsonDecode(response.body);
    response = data;
    if (data['status'] == "ok") {
      setState(() {
        print("inside setstate");
      });
    } else {
      throw Exception();
    }
  }

  openWebview(index) async {
    String url = response.articles[index].url;
    if (await canLaunch(url)) {
      launch(url);
      print("Inside Open Web View");
    } else
      throw 'Can not launch';
  }

  @override
  Widget build(BuildContext context) {
    // return Container();
    return RefreshIndicator(
      child: response != null
          ? ListView.builder(
              itemCount: response["articles"].length,
              itemBuilder: (context, index) {
                nsd = NewsDetails.fromJson(response["articles"][index]);
                return InkWell(
                    onTap: () {
                      openWebview(index);
                    },
                    child: Card(
                        elevation: 10,
                        child: nsd.urlToImage != null && nsd.title != null
                            ? Container(
                                padding: EdgeInsets.all(5),
                                child: Column(
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.circular(20),
                                      child: Image.network("${nsd.urlToImage}"),
                                    ),
                                    Padding(
                                      padding: EdgeInsets.all(10),
                                    ),
                                    Text(
                                      "${nsd.title}",
                                      style: TextStyle(
                                          fontSize: 18,
                                          fontWeight: FontWeight.bold),
                                    ),
                                    Padding(
                                      padding: EdgeInsets.all(5),
                                    ),
                                    Text("${nsd.description}"),
                                    Padding(
                                      padding: EdgeInsets.all(10),
                                    ),
                                  ],
                                ),
                              )
                            : Container()));
              },
            )
          : Center(child: CircularProgressIndicator()),
      onRefresh: () {
        return Future.delayed(Duration(seconds: 1), () {
          setState(() {
            print("Inside Refresh");
          });
        });
      },
    );
  }
}
